config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :product_imports
  end
end

app/models/spree/product_import.rb
# This model is the master routine for uploading products
# Requires Paperclip and CSV to upload the CSV file and read it nicely.

# Original Author:: Josh McArthur
# License:: MIT
module Spree
  class ProductError < StandardError;
  end;
  class ImportError < StandardError;
  end;
  class SkuError < StandardError;
  end;

  class ProductImport < ActiveRecord::Base

    ENCODINGS= %w(UTF-8 iso-8859-1)

    has_attached_file :data_file

    #Content type of csv vary in different browsers.
    validates_attachment :data_file, content_type: {content_type: ["text/csv", "text/plain", "text/comma-separated-values", "application/octet-stream", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]}
    after_destroy :destroy_products

    serialize :product_ids, Array
    cattr_accessor :settings

    def products
      Product.where :id => product_ids
    end

    require 'csv'
    require 'pp'
    require 'open-uri'

    def destroy_products
      products.destroy_all
    end

    state_machine :initial => :created do

      event :start do
        transition :to => :started, :from => :created
      end
      event :complete do
        transition :to => :completed, :from => :started
      end
      event :failure do
        transition :to => :failed, :from => [:created, :started]
      end

      before_transition :to => [:failed] do |import|
        import.product_ids = []
        import.failed_at = Time.now
        import.completed_at = nil
      end

      before_transition :to => [:completed] do |import|
        import.failed_at = nil
        import.completed_at = Time.now
      end
    end
    #Return the number of rows in CSV.
    def productsCount
      if Rails.env.production?
        @file = ENV.fetch("CDN_HOST_ALL") + self.data_file.path
      else
        @file = self.data_file.path
      end
      rows = open_spreadsheet(@file)

      #rows = CSV.parse(open(self.data_file.url).read, :col_sep => ",", :quote_char => "'")
      return rows.count
    end

    # def import
    #   rows = CSV.parse(open(self.data_file.url).read)
    #   delayed=rows.count>Spree::ProductImport.settings[:num_prods_for_delayed]
    #   if (delayed)
    #     ImportProductsJob.perform_later(self.id)
    #   else
    #     import_data!(Spree::ProductImport.settings[:transaction])
    #   end
    #   return delayed
    # end

    def state_datetime
      if failed?
        failed_at
      elsif completed?
        completed_at
      else
        updated_at
      end
    end

    def import_data!(_transaction=true)
      start
      if _transaction
        transaction do
          _import_data
        end
      else
        _import_data
      end
    end

    def _import_data
      begin
        log("import data start", :debug)
        @products_before_import = Spree::Product.all
        @skus_of_products_before_import = @products_before_import.map(&:sku)
        if Rails.env.production?
          @file = ENV.fetch("CDN_HOST_ALL") + self.data_file.path
        else
          @file = self.data_file.path
        end



        rows = open_spreadsheet(@file)

        if ProductImport.settings[:first_row_is_headings]
          col = get_column_mappings(rows.row(1))

        else
          col = ProductImport.settings[:column_mappings]

        end

        (2..rows.last_row).each do |i|
          row = rows.row(i)
          product_information = {}

          #Automatically map 'mapped' fields to a collection of product information.
          #NOTE: This code will deal better with the auto-mapping function - i.e. if there
          #are named columns in the spreadsheet that correspond to product
          # and variant field names.

          col.each do |key, value|
            #Trim whitespace off the beginning and end of row fields
            row[value].try :strip!
            product_information[key] = row[value]
          end

          #Manually set available_on if it is not already set
          product_information[:available_on] = Date.today - 1.day if product_information[:available_on].nil?

          if (product_information[:shipping_category_id].nil?)
            sc = Spree::ShippingCategory.first
            product_information[:shipping_category_id] = sc.id unless sc.nil?
          end
          if (product_information[:tax_category_id].nil?)
            tc = Spree::TaxCategory.where(is_default: true).first
            product_information[:tax_category_id] = tc.id unless tc.nil?
          end

          log("#{pp product_information}", :debug)

          variant_comparator_field = ProductImport.settings[:variant_comparator_field].try :to_sym
          variant_comparator_column = col[variant_comparator_field]


          if ProductImport.settings[:create_variants] and variant_comparator_column and row[variant_comparator_column]!= nil and
              #p = Product.with_translations().where(Product.table_name+'.'+variant_comparator_field.to_s => row[variant_comparator_column]).first #only(:product,:where)
              p = Product.where(variant_comparator_field.to_s => row[variant_comparator_column].downcase).first #only(:product,:where)
            # Product exists
            p.update_attribute(:deleted_at, nil) if p.deleted_at #Un-delete product if it is there
            p.variants.each {|variant| variant.update_attribute(:deleted_at, nil)}
            update_product(p, product_information)
          else
            #product doesn't exists
            if p = Product.where(:name => product_information[:name], :description => product_information[:description]).first
              # Product exists
              p.update_attribute(:deleted_at, nil) if p.deleted_at #Un-delete product if it is there
              p.variants.each {|variant| variant.update_attribute(:deleted_at, nil)}
              update_product(p, product_information)
            else
              if (@skus_of_products_before_import.include?(product_information[:sku]))
                log(msg="SKU #{product_information[:sku]} exists, but slug #{prod.slug} not exists!! ", :error)
                raise ProductError, msg
              end

              next unless create_product(product_information)
            end
          end
        end

        #2BeDigital.We disable this option
        #if ProductImport.settings[:destroy_original_products]
        #@products_before_import.each { |p| p.destroy }
        #end
      end
      # Finished Importing!
      complete
      return [:notice, "Product data was successfully imported."]
    end

    private

    def open_spreadsheet(file)
      case File.extname(file)
        when ".csv" then
          Roo::CSV.new(file)
        when ".xls" then
          Roo::Excel.new(file)
        when ".xlsx" then
          Roo::Excelx.new(file)
        else
          raise "Unknown file type: #{file}"
      end
    end

    def create_product(params_hash)

      log("CREATE PRODUCT:"+params_hash.inspect)

      product = Product.new
      properties_hash = Hash.new

      #2BeDigital: Manually set retail_only if it is not already set
      params_hash[:retail_only] = 0 if params_hash[:retail_only].nil?

      # Array of special fields. Prevent adding them to properties.
      special_fields = ProductImport.settings.values_at(
          :image_fields,
          :taxonomy_fields,
          :store_field,
          :variant_comparator_field
      ).flatten.map(&:to_s)


      params_hash.each do |field, value|
        if (field.to_s.eql?('master_price'))
          product.price=value
        elsif (field.to_s.eql?('sku'))
          product.sku="default"
        elsif (product.respond_to?("#{field}="))
          product.send("#{field}=", value)
        elsif not special_fields.include?(field.to_s) and property = Property.where("lower(name) = ?", field).first and value.present?
          properties_hash[property] = value.capitalize
        end
      end
      if params_hash[:sku] == "default"
        save_product(product, params_hash, properties_hash, true, "new")
      else
        save_product(product, params_hash, properties_hash, true, "new")
      end


    end

    def update_product(product, params_hash)

      log("UPATE PRODUCT:"+params_hash.inspect)
      properties_hash = Hash.new

      #2BeDigital: If exists retail_only key without value, we assign false, to avoid null values.
      if (params_hash.key?(:retail_only) and params_hash[:retail_only].nil?)
        params_hash[:retail_only] = 0
      end

      # Array of special fields. Prevent adding them to properties.
      special_fields = ProductImport.settings.values_at(
          :image_fields,
          :taxonomy_fields,
          :store_field,
          :variant_comparator_field
      ).flatten.map(&:to_s)

      # Here we only update product fields, because we update or create variant
      # after update the product.
      product_fields=product.attribute_names
      product_hash=Hash.new
      params_hash.each do |key, value|
        if product_fields.include?(key.to_s)
          product_hash[key]=value
        end
      end
      # We only assign fields of the products table.
      params_hash.each do |field, value|
        if (product_fields.include?(field.to_s))
          if (product.respond_to?("#{field}=") and params_hash[:locale].nil?)
            product.send("#{field}=", value)
          end
        elsif not special_fields.include?(field.to_s) and property = Property.where("lower(name) = ?", field).first
          properties_hash[property] = value.capitalize! unless value.nil?
        end
      end

      save_product(product, params_hash, properties_hash, false, "no")
    end


app/controllers/spree/admin/product_imports_controller.rb
module Spree
  module Admin
    class ProductImportsController < BaseController

      def index
        @product_import = Spree::ProductImport.new
      end

      def show
        @product_import = Spree::ProductImport.find(params[:id])
        @products = @product_import.products
      end

      def create
        @product_import = Spree::ProductImport.create(product_import_params)
				@product_import.created_by=spree_current_user.id
				@product_import.save
        begin
          numProds=@product_import.productsCount
          if numProds > Spree::ProductImport.settings[:num_prods_for_delayed]
						ImportProductsJob.perform_later(@product_import.id)
					  flash[:notice] = t('product_import_processing')
          else
            @product_import.import_data!(Spree::ProductImport.settings[:transaction])
					  flash[:success] = t('product_import_imported')
            end
        rescue StandardError => e
          @product_import.error_message=e.message
          @product_import.failure
          if (e.is_a?(OpenURI::HTTPError))
            flash[:error] = t('product_import_http_error')
          else
            flash[:error] = e.message
          end
        end
        redirect_to admin_product_imports_path
      end

      def destroy
        @product_import = Spree::ProductImport.find(params[:id])
        if @product_import.destroy
          flash[:success] = t('delete_product_import_successful')
        end
        redirect_to admin_product_imports_path
      end

      private
        def product_import_params
          params.require(:product_import).permit!
        end
    end
  end
end

app/views/spree/admin/product_imports/index.html.erb
<% content_for :page_title do %>
  <%= t('form.product_import.heading') %>
<% end %>

<div class="row">
<div class="col-sm-6">
<%= form_for([:admin, @product_import], :method => :post, :html => { :multipart => true }) do |f| %>
  <fieldset class="no-border-top">
  <%= f.field_container :data_file, class: ['form-group'] do  %>
    <%= f.label :data_file, t('form.product_import.new.data_file') %><br />
    <%= f.file_field :data_file %>
    <%= f.error_message_on :data_file %>
  <% end %>
  <div class="field">
    <%= f.label :separatorChar, t('form.product_import.separator_char') %><br />
    <%= f.text_field :separatorChar, class: 'form-control required',:id =>  "separatorChar",:value => ";" ,:size => 1, :maxlength => 1 %>
  </div>
  <div class="field">
    <%= f.label :encoding_csv, t('form.product_import.encoding') %><br />
    <%= f.select(:encoding_csv,
                   options_from_collection_for_select(Spree::ProductImport::ENCODINGS, :to_s, :to_s, 'UTF-8'),
                   {:class => 'select2', :prompt => false}) %>
  </div>
  <div data-hook="buttons" class="form-actions">
    <%= button Spree.t('actions.import'), 'ok', 'submit', {class: 'btn-success'} %>
  </div>
  </fieldset>

<% end %>
</div>
</div>
<table class="table">
  <colgroup>
    <col style="width: 15%">
    <col style="width: 20%">
    <col style="width: 10%">
    <col style="width: 15%">
    <col style="width: 10%">
    <col style="width: 20%">
    <col style="width: 5%">
  </colgroup>
  <thead>
  <tr>
    <th>Date creation</th>
    <th>CSV Name</th>
    <th>Status</th>
    <th>Date Status</th>
    <th>Imported</th>
    <th>Error Message</th>
    <th class="actions">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% Spree::ProductImport.order("created_at DESC").all.each do |import| %>
    <tr class="<%= cycle('odd', 'even') %>" id="<%= dom_id import %>">
      <td><%= I18n.l(import.created_at.to_datetime,format: :short)%></td>
      <td><%= link_to import.data_file_file_name, import.data_file.url -%></td>
      <td><span class="label-<%= import.state.downcase %>"><%= t(import.state, :scope => "product_import.state")%></span></td>
      <td><%= I18n.l(import.state_datetime.to_datetime,format: :short) %></td>
      <td><%= import.product_ids.size -%></td>
      <td><%= import.error_message%></td>
      <td class="actions text-center">
        <%= link_to_edit import, :url => admin_product_import_path(import), :no_text => true -%>
      </td>
      <td class="actions text-center">
        <%= link_to_delete import, :url => admin_product_import_path(import), :no_text => true -%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/product_imports/show.html.erb
<% content_for :page_title do %>
  <%= t(:show_product_import) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to t(:back_to_product_imports), admin_product_imports_path, :icon => 'icon-arrow-left' %>
    <%= button_link_to t(:delete_product_import), admin_product_import_path(@product_import), {:icon => 'icon-remove', :method => :delete, :confirm => t("confirm_delete_product_import")} %>
<% end %>

<table class="table" id="listing_products">
  <colgroup>
    <col style="width: 20%">
    <col style="width: 50%">
    <col style="width: 20%">
    <col style="width: 10%">
  </colgroup>
  <thead>
    <tr data-hook="admin_products_index_headers">
      <th><%= t(:sku) %></th>
      <th><%= t(:name) %></th>
      <th><%= t(:master_price) %></th>
      <th class="actions" data-hook="admin_products_index_header_actions"></th>
    </tr>
 </thead>
 <tbody>
 <% @products.each do |product| %>
  <tr class="<%= cycle('odd', 'even') %>" <%= "style='color: red;'" if product.deleted? %> id="<%= dom_id product %>" data-hook="admin_products_index_rows">
    <td><%= product.sku rescue '' %></td>
    <td><%= product.name rescue '' %></td>
    <td><%= number_to_currency product.price rescue '' %></td>
    <td class="actions" data-hook="admin_products_index_row_actions">
      <%= link_to_edit_url edit_admin_product_path(product), :no_text => true unless product.deleted? %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>